### PR TITLE
Adding contributors

### LINKED ISSUE #307: Add contributors to Readme
Add Contributors to Readme

### PR DESCRIPTION
**Pull request by saiyam1814**
fixes #307

### CODE REVIEW

**Comment by saiyam1814** [comment]
@chmod-777-shauli

**Comment by dwertent** [comment]
Hi @saiyam1814  and thank you for contributing.
Can you please reopen this PR against the dev branch? Thank you :)

**Comment by saiyam1814** [comment]
> Hi @saiyam1814 and thank you for contributing. Can you please reopen this PR against the dev branch? Thank you :)

Done #309

**Comment by dwertent** [comment]
Reopened to dev

**Pull request closed without merging**
