### PR TITLE
docs: Add Swagger Support

### PR DESCRIPTION
**Pull request by vladklokun**
## What this PR does

This PR adds a Swagger spec for the Kubescape microservice API.

The Spec is a manually written OpenAPI 3.0.1 specification in YAML format.

## Reasoning

The two possible approaches to supporting Swagger documentation is writing the spec manually or automatically generating it from code.

### Automatic generation

Automatic generation would allow generating a Swagger spec from structs actually used in the project. Tools achieve that by inspecting the Request and Response structs’ annotations. However, since the Kubescape microservice uses structs defined in another package, automatically generating the Swagger Spec would require large changes, either:
- moving to a different HTTP framework that both defines the request and response structs and generates a Swagger spec from them (e.g. [swaggest/rest](https://github.com/swaggest/rest)).
- annotating structs defined in dependencies (e.g `utilsv1meta`) with tags used by tools that generate Swagger specs.
- manually writing Go documentation files that define the request and response structs, annotating them with Swagger tags and then generating an OpenAPI v2 spec using [go-swagger](https://github.com/go-swagger/go-swagger), preferably, in CI/CD.

Moving to a different framework requires too much effort and does not look like a priority right now. Annotating structs in a dependency would force us to introduce changes upstream and constantly maintain them, which seems counterintuitive and tedious down the road.

Manually writing Go documentation files that describe the requests and response and autogenerating a Swagger schema is an option that comes with significant drawbacks:
- it supports only the OpenAPI 2.0 spec, which lacks features like Type Composition. The latest version is 3.0, which does not have this problem.
- it has flaky support for Enums. For example, go-swagger generates redundant descriptions for Enum values.
- it boils down to manually writing a Swagger spec, but with an extra step of generating it from the documentation files, since Kubescape would not use the documented structs for handling HTTP request, while also limiting the scope of OpenAPI features that can be used.
- alternatively, actually using the documented structs for handling HTTP requests would not only require a refactoring, but also keep the limitation of OpenAPI features we can use to document the API.

### Manual writing
Forgoing automatic generation — which is not strictly automatic, as shown — leaves us with manually writing the spec. 
While somewhat inconvenient and prone to errors, it allows us to use any OpenAPI version and feature we want to. This ensures we can document our API however we want, not being limited by an autogeneration tool and the features it supports. Compared to keeping separate Go documentation files, it also eliminates an extra step of generating the Spec from docfiles, which would have to be written manually and separately from the actual structs in use anyway.

Therefore, I believe that a manual OpenAPI 3.0 spec is the way to go. For the current version of the API, that is :wink:

### CODE REVIEW

**Review by dwertent — APPROVED** [review]
If it possible to share a screenshot of how the swagger webpage will look like. It will be easier to understand what are the different values and the different fields.

**Comment by vladklokun** [comment]
Here are the resultsing UIs served directly from the Kubescape Microservice.

## SwaggerUI
image

## RapiDoc
NB: The screenshot is truncated since the main contents have a scrollable viewport.

image

## Redoc
NB: Redoc does not provide the ability to try out the documented APIs in its open-source product.

image

**Comment by dwertent** [comment]
@vladklokun Do you need to update kubescape with the merged opa-utils?

**Comment by vladklokun** [comment]
Yup, I do in the long run.

But in the meantime, I vendored the modules and generated the spec. So the included spec is up-to-date.

**Review by dwertent — APPROVED** [review]

**Pull request merged**
