### PR TITLE
Prometheus metrics server and example deployments

### PR DESCRIPTION
**Pull request by Joibel**
#202 parts 2 and 3

This adds a metrics command to kubescape to start a web server. It will scan in the background and update frameworks in the background, whilst serving scan results on /metrics

Also includes an example deployment of this.

### CODE REVIEW

**Comment by yonahd** [comment]
@Joibel isn't kubescape supposed to run as a job and than exit? When would prometheus query the data you export and if it waits when do you tell it to exit? Or is the scheduling of the scanning done inside the service itself?

**Comment by Joibel** [comment]
@yonahd yes, traditionally it ran as a job and exited.

Prometheus runs as a continuous process. It's design is to go out to external data sources and scrape them on a periodic basis. So something needs to serve the kubescape results over http so that prometheus can scrape the values from it.

So I've added a mode to kubescape to run as an http server to do this job. It doesn't have to be done this way, and I did explore other options. You could for example run nginx calling kubescape to perform scrapes on demand.

The scrape on demand model doesn't work very well (I wrote it this way to start with) because even on my relatively modest cluster a scrape takes longer than 10 seconds, and not responding to http for that long is bad practice. We could concoct a much more complex container which scraped in the background, putting its results in a location that a web server can serve, but this is not very good container form, you shouldn't really have multiple processes and run cron jobs. A multicontainer image would work in kubernetes, and should this pull request get rejected I'll probably end up doing it that way.

So this container runs a background thread collecting scans and periodically doing downloads, so yes, the scheduling is done inside clihandler/cmd/metrics.go:backgroundScanner(). The web server sits there serving the results of those scans. It expects to sit there running forever, and only terminates when the pod is terminated. Having a permanently running pod is the only sane solution for a prometheus monitor as it would expect to be able to go and get results on its own schedule.

**Comment by yonahd** [comment]
@Joibel got it makes sense.
It is a little strange but I guess the user can restart the deployment /scan using something like this
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deployment-restart
  namespace: <YOUR NAMESPACE>
spec:
  concurrencyPolicy: Forbid
  schedule: '0 8 * * *' # cron spec of time, here, 8 o'clock
  jobTemplate:
    spec:
      backoffLimit: 2 # this has very low chance of failing, as all this does
                      # is prompt kubernetes to schedule new replica set for
                      # the deployment
      activeDeadlineSeconds: 600 # timeout, makes most sense with 
                                 # "waiting for rollout" variant specified below
      template:
        spec:
          serviceAccountName: deployment-restart # name of the service
                                                 # account configured above
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl # probably any kubectl image will do,
                                     # optionaly specify version, but this
                                     # should not be necessary, as long the
                                     # version of kubectl is new enough to
                                     # have `rollout restart`
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/<YOUR DEPLOYMENT 
```

**Comment by Joibel** [comment]
I'm not sure why you'd want to restart the deployment on a 
Internally when you run kubescape metrics it will rescan every 5 minutes (-i parameter) and redownload the framework every 4 hours (-u parameter). Kubescape metrics is calling kubescape scan internally.
The restart would just interfere with that. It would update kubescape if you were using an image tag that moved for the deployment, like :latest. (And had an imagePull Policy of Always). However, for properly secure and managed environments it'd be preferable to run a known tag and update that through some management mechanism like gitops so you knew which containers you were running.

**Comment by yonahd** [comment]
@Joibel didn't see you added these flags.
Makes sense now. Thanks for clarifying

**Comment by Joibel** [comment]
No problem @yonahd. I've had my head in prometheus for weeks now doing various things, and it took a long time to get my head around how it fits into things.

**Comment by Joibel** [comment]
Hi @yonahd. This has stalled and I'm not sure whether the code has fundamental issues you're unhappy with or whether you'd like to merge it and you want me to just resolve the merge conflicts?

**Comment by dwertent** [comment]
Hi @Joibel, we did not accept this yet mainly because we already have a different architecture of running Kubescape as a server.

If it's ok by you, I will contact you in private so we can talk this in through :)

**Comment by Joibel** [comment]
@dwertent OK. I'll be around on discord, so we can chat there.

**Comment by james1miller93** [comment]
@Joibel I really like the idea here and we'd like to adopt this method of running kubescape to build some prometheus alerts and grafana dashboards around the service.

@dwertent Can you provide any pointers on the method of running kubescape as a server you mentioned above?

**Comment by dwertent** [comment]
@james1miller93 We are working on the development of the server, thanks to @Joibel who gave us a very useful input regarding prometheus support.
This feature will officially be released in the close few weeks, since we are currently working on some other features...

**Comment by adberger** [comment]
@dwertent any update on this?

**Comment by dwertent** [comment]
Hi @adberger , I published a beta version.
You can see here the [yaml](https://github.com/dwertent/kubescape/blob/server-support/httphandler/ks-prometheus-support.yaml), [readme](https://github.com/dwertent/kubescape/tree/server-support/httphandler#readme), and the [source code](https://github.com/dwertent/kubescape/blob/server-support/httphandler/prometheus.go). (Ignore the rest of the files in the directory).
This is a beta version, the official release will be available in the close few weeks.

We will approve the prometheus format output and build a better wrapper for the microservice.

**Comment by adberger** [comment]
> Hi @adberger , I published a beta version. You can see here the [yaml](https://github.com/dwertent/kubescape/blob/server-support/httphandler/ks-prometheus-support.yaml), [readme](https://github.com/dwertent/kubescape/tree/server-support/httphandler#readme), and the [source code](https://github.com/dwertent/kubescape/blob/server-support/httphandler/prometheus.go). (Ignore the rest of the files in the directory). This is a beta version, the official release will be different and will be available in the close few weeks (This is why I did not except the PR).
> 
> We will approve the prometheus format output and build a better wrapper for the microservice.

Thank you!
Works fine for me, although I needed to increase the scraping interval & timeout, which makes sense considering the whole cluster gets scanned on each call.

If anyone is interested, here is what I did:

Deploy kubescape
```
kubectl apply -f https://raw.githubusercontent.com/dwertent/kubescape/server-support/httphandler/ks-prometheus-support.yaml
```

Edit kubescape Deployment
```
kubectl edit deploy kubescape -n ks-scanner
```
Add 'name: http' to ports:
```
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

Deploy kube-prometheus-stack
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false,prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false
```

Deploy PodMonitor (podmonitor.yaml)
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubescape
  labels:
    app: kubescape
spec:
  selector:
    matchLabels:
      app: kubescape
  podMetricsEndpoints:
  - port: http
    interval: 60s
    scrapeTimeout: 30s
```

`kubectl apply -f podmonitor.yaml -n ks-scanner`

**Comment by dwertent** [comment]
I pushed to dev the official Prometheus support.
Please follow [here](https://github.com/armosec/kubescape/tree/dev/httphandler/examples/prometheus). We will make some more changes but this is already better than what we have now.

Please feel free to share your feedback :)

**Comment by dwertent** [comment]
It's official, we added [Prometheus support](https://hub.armo.cloud/docs/installation-of-armo-in-cluster#prometheus-support)!!

**Pull request closed without merging**
