### PR TITLE
Helm: add value to set frameworks

### PR DESCRIPTION
**Pull request by g-linville**
This commit adds a new value to the Helm chart which allows the user to specify specific frameworks to scan. Right now only `nsa` is hardcoded into the CronJob, so this allows for greater customization for users who want to use MITRE, ArmoBest, or custom frameworks.

### CODE REVIEW

**Comment by dwertent** [comment]
Thank you @g-linville for this contribution 😀
This might be confusing but the helm charts are stored in a different repo - [armo-helm](https://github.com/armosec/armo-helm).

If you wish, you can contribute very similar code [here](https://github.com/armosec/armo-helm/blob/master/charts/armo-components/templates/armo-kubescape-job.yaml#L40) and [here](https://github.com/armosec/armo-helm/blob/master/charts/armo-components/templates/armo-kubescape-cronjob.yaml#L45). 

Notice, the command is `kubescape scan` which means kubescape will scan all frameworks, you can change it to be `kubescape scan framework {{ $frameworks }}` and the default value should be `all` (and not `nsa`).
 
@slashben We should remove the helm chart from the kubescape repo to prevent further confusion

**Comment by slashben** [comment]
Agreed, let's leave there a note that this has been moved

**Comment by g-linville** [comment]
Thanks for the info @dwertent. I did not realize this was not the official Helm chart, lol.

**Comment by dwertent** [comment]
@g-linville Sorry, my bad for not removing it from the repo :(

**Pull request closed without merging**
