### PR TITLE
docs: update homebrew installation

### PR DESCRIPTION
**Pull request by chenrui333**
👋  I have helped [creating the formula](https://github.com/Homebrew/homebrew-core/pull/95034) in homebrew-core, it would help future installation and upgrades. Let me know what you think. Thanks!

### CODE REVIEW

**Comment by dwertent** [comment]
I'm afraid I do not understand homebrew enough (I don't work with mac). @rotemamsa  what do you think?
@chenrui333 How do other releases work? Is there always a mismatch and how do they update versions?
Currently we use [this](https://github.com/armosec/homebrew-kubescape) repo for updating the version.

**Comment by rotemamsa** [comment]
Hi there  @chenrui333 !
i see that in this commit:
https://github.com/Homebrew/homebrew-core/pull/95034/files 
you specify "hard coded" version (147) in url path. can you please explain why is that? we see that when we are running "brew install kubescape" we are sill installing 2.0.147, and it might be related. 

thanks!
Rotem

**Comment by chenrui333** [comment]
> I'm afraid I do not understand homebrew enough (I don't work with mac). @rotemamsa what do you think? @chenrui333 How do other releases work? Is there always a mismatch and how do they update versions? Currently we use [this](https://github.com/armosec/homebrew-kubescape) repo for updating the version.

you can use this to autobump the release, https://github.com/mislav/bump-homebrew-formula-action

**Comment by chenrui333** [comment]
> you specify "hard coded" version (147) in url path. can you please explain why is that? we see that when we are running "brew install kubescape" we are sill installing 2.0.147, and it might be related.

that is because we want to snapshot the version and the checksum.

**Comment by chenrui333** [comment]
or if you want to do it manually, you can also run `brew bump-formula-pr kubescape --version=x.x.x` to bump the formula. Let me know if that makes sense.

**Comment by amirmalka** [comment]
@chenrui333 Recently we made a few changes in our build process that involve using the git2go go package, which depends on libgit2 library. We are facing some issues related to the upgrade of the existing formula and I was hoping to get your advice on this. 
See https://github.com/Homebrew/homebrew-core/pull/106523

**Comment by chenrui333** [comment]
I think we can revisit this PR as it is buildable in the [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/124725) now.

**Comment by dwertent** [comment]
@chenrui333 The branch was deleted.
Do you want to re-open this PR?

**Pull request closed without merging**
